#!/bin/sh

case "$1" in
    configure)
        adduser --system --home /var/lib/uncloud --shell /usr/sbin/nologin --group uncloud || true
        systemctl daemon-reload
        systemctl enable uncloud.service
        exit 0
        ;;

    abort-upgrade)
        exit 0
        ;;

    abort-remove|abort-deconfigure)
        exit 0
        ;;

    *)
        exit 1
        ;;
esac
